export const SPHERES = {
  SUN: "Sun",
  MERCURY: "Mercury",
  VENUS: "Venus",
  EARTH: "Earth",
  MARS: "Mars",
  JUPITER: "Jupiter",
  SATURN: "Saturn",
  URANUS: "Uranus",
  NEPTUNE: "Neptune",
} as const;

export type Sphere = (typeof SPHERES)[keyof typeof SPHERES];

export const sphereData = [
  {
    title: SPHERES.MERCURY,
    orbitRadius: 4,
    orbitSpeed: 0.8,
    rotationSpeed: 0.004,
    texture: "/src/assets/uv-maps/mercury-uv/mercury.jpg",
    sphereArgs: [0.38, 32, 32] as [number, number?, number?],
    sunIntensity: 1.2,
    nightDarkness: 0.05,
    id: 0,
  },
  {
    title: SPHERES.VENUS,
    orbitRadius: 7,
    orbitSpeed: 0.6,
    rotationSpeed: 0.002,
    texture: "/src/assets/uv-maps/venus-uv/venus.jpg",
    sphereArgs: [0.95, 32, 32] as [number, number?, number?],
    sunIntensity: 1,
    nightDarkness: 0.05,
    id: 1,
  },
  {
    title: SPHERES.EARTH,
    orbitRadius: 10,
    orbitSpeed: 0.5,
    rotationSpeed: 0.01,
    texture: "/src/assets/uv-maps/earth-uv/earth-day.jpg",
    sphereArgs: [1, 32, 32] as [number, number?, number?],
    sunIntensity: 1.5,
    nightDarkness: 0.05,
    id: 2,
  },
  {
    title: SPHERES.MARS,
    orbitRadius: 13,
    orbitSpeed: 0.4,
    rotationSpeed: 0.01,
    texture: "/src/assets/uv-maps/mars-uv/mars.jpg",
    sphereArgs: [0.53, 32, 32] as [number, number?, number?],
    sunIntensity: 1,
    nightDarkness: 0.05,
    id: 3,
  },
  {
    title: SPHERES.JUPITER,
    orbitRadius: 16,
    orbitSpeed: 0.3,
    rotationSpeed: 0.02,
    texture: "/src/assets/uv-maps/jupiter-uv/jupiter.jpg",
    sphereArgs: [1.12, 32, 32] as [number, number?, number?],
    sunIntensity: 1,
    nightDarkness: 0.05,
    id: 4,
  },
  {
    title: SPHERES.SATURN,
    orbitRadius: 20,
    orbitSpeed: 0.2,
    rotationSpeed: 0.018,
    texture: "/src/assets/uv-maps/saturn-uv/saturn.jpg",
    sphereArgs: [0.94, 32, 32] as [number, number?, number?],
    sunIntensity: 1,
    nightDarkness: 0.05,
    id: 5,
  },
  {
    title: SPHERES.URANUS,
    orbitRadius: 24,
    orbitSpeed: 0.15,
    rotationSpeed: 0.015,
    texture: "/src/assets/uv-maps/uranus-uv/uranus.jpg",
    sphereArgs: [0.4, 32, 32] as [number, number?, number?],
    sunIntensity: 1,
    nightDarkness: 0.05,
    id: 6,
  },
  {
    title: SPHERES.NEPTUNE,
    orbitRadius: 28,
    orbitSpeed: 0.1,
    rotationSpeed: 0.012,
    texture: "/src/assets/uv-maps/neptune-uv/neptune.jpg",
    sphereArgs: [0.38, 32, 32] as [number, number?, number?],
    sunIntensity: 1,
    nightDarkness: 0.05,
    id: 7,
  },
];
